varlist <- as.data.frame(table(sort(trial1$Variant_Classification)))
View(varlist)
trial2 <- data.frame(trial1$Variant_Classification, trial1)
View(trial2)
Missense <- trial2 %>%  filter(trial1.Variant_Classification=='Missense_Mutation')
library(dplyr)
Missense <- trial2 %>%  filter(trial1.Variant_Classification=='Missense_Mutation')
View(Missense)
Missense <- trial2 %>%  filter(trial1.Variant_Classification=='Missense_Mutation')
Nonsense <- trial2 %>%  filter(trial1.Variant_Classification=='Nonsense_Mutation')
Nonstop<- trial2 %>%  filter(trial1.Variant_Classification=='Nonstop_Mutation')
View(Missense)
View(Nonsense)
View(Nonstop)
Splice <- trial2 %>%  filter(trial1.Variant_Classification=='Splice_Site')
Translation_SS <-  trial2 %>%  filter(trial1.Variant_Classification=='Translation_Start_Site')
View(Splice)